[package]
name = "loomtv-tauri"
version = "1.0.31"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "2", features = ["image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
rusqlite = { version = "0.32", features = ["bundled"] }
base64 = "0.22"
hmac = "0.12"
mdns-sd = { version = "0.19.2", default-features = false }
rand = "0.8"
sha2 = "0.10"
tauri-plugin-updater = "2"

[build-dependencies]
tauri-build = { version = "2", features = ["config-json"] }

[dev-dependencies]
tempfile = "3"
