allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  ffmpeg-static: true
  fs-xattr: true
  macos-alias: true
  unrs-resolver: true
blockExoticSubdeps: false
# 24 hour delay before pnpm accepts newly published package versions.
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - pnpm
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
nodeLinker: hoisted
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
