import { StyleSheet } from 'react-native';

function colorWithOpacity(color: string, opacity: number): string {
  const match = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(color);
  if (!match) return color;
  const [, red, green, blue] = match;
  return `rgba(${Number.parseInt(red, 16)},${Number.parseInt(green, 16)},${Number.parseInt(blue, 16)},${opacity})`;
}

export type MobileThemeColors = {
  accent: string;
  accentSoft: string;
  accentBorder: string;
  accentForeground: string;
  bg: string;
  panel: string;
  panel2: string;
  border: string;
  text: string;
  muted: string;
  faint: string;
  themeLabel: string;
};

export const settingsContentMaxWidth = 640;
const settingsMetricGap = 8;
export function createStyles(theme: MobileThemeColors) {
  const { accent, accentSoft, accentBorder, accentForeground, bg, panel, panel2, border, text, muted, faint } = theme;
  const isDarkTheme = text !== '#000000';
  const surface = panel2;
  const dangerText = isDarkTheme ? '#ff9a8f' : '#b42318';
  const errorTextColor = isDarkTheme ? '#ff8c78' : '#b42318';
  const ratingSurface = isDarkTheme ? 'rgba(245,196,81,0.15)' : '#fff1bf';
  const posterRatingSurface = 'rgba(0,0,0,0.78)';
  const posterRatingBorder = 'rgba(245,196,81,0.42)';
  const posterRatingTextColor = '#f5c451';
  const ratingBorder = isDarkTheme ? 'rgba(245,196,81,0.42)' : '#f5c451';
  const ratingText = isDarkTheme ? '#f5c451' : '#000000';
  return StyleSheet.create({
  app: {
    backgroundColor: bg,
    flex: 1,
  },
  imageLoadFrame: {
    backgroundColor: panel2,
    overflow: 'hidden',
  },
  shimmerBase: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: panel2,
    overflow: 'hidden',
  },
  shimmerBand: {
    // The width and gradient sheen are applied at runtime; the vertical overflow
    // keeps the skewed edges clipped off-frame.
    bottom: -40,
    position: 'absolute',
    top: -40,
  },
  pairingAvoider: {
    flex: 1,
  },
  pairingContent: {
    flexGrow: 1,
    gap: 28,
    justifyContent: 'center',
    paddingBottom: 64,
    paddingHorizontal: 24,
    paddingTop: 48,
  },
  pairingContentKeyboard: {
    justifyContent: 'flex-start',
    paddingBottom: 32,
    paddingTop: 24,
  },
  pairingHero: {
    alignItems: 'center',
    gap: 14,
  },
  pairingSubtitle: {
    color: muted,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 320,
    textAlign: 'center',
  },
  helpToggle: {
    alignItems: 'center',
    minHeight: 40,
    justifyContent: 'center',
  },
  helpToggleText: {
    color: accent,
    fontSize: 14,
    fontWeight: '600',
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  formBlock: {
    gap: 11,
    paddingTop: 8,
  },
  discoveryBlock: {
    gap: 10,
  },
  discoveryHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 28,
  },
  discoveryTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '700',
  },
  refreshDiscoveryButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 4,
  },
  hostCard: {
    alignItems: 'center',
    backgroundColor: surface,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  hostCardSelected: {
    backgroundColor: accentSoft,
    borderColor: accent,
  },
  hostCardCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  hostName: {
    color: text,
    fontSize: 16,
    fontWeight: '700',
  },
  hostAddress: {
    color: faint,
    fontSize: 12,
  },
  hostConnectLabel: {
    color: accent,
    fontSize: 13,
    fontWeight: '700',
  },
  emptyDiscoveryCard: {
    alignItems: 'center',
    backgroundColor: surface,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 5,
    padding: 20,
  },
  emptyDiscoveryTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDiscoveryCopy: {
    color: muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  manualForm: {
    gap: 11,
  },
  inputField: {
    gap: 6,
  },
  inputLabel: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
  },
  manualHint: {
    color: faint,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  savedHostCard: {
    backgroundColor: surface,
    borderColor: border,
    borderRadius: 14,
    borderWidth: 1,
    gap: 5,
    padding: 18,
  },
  hostStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 7,
  },
  hostStatusDot: {
    backgroundColor: '#ef6a5b',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  hostStatusDotSearching: {
    backgroundColor: accent,
  },
  savedHostStatus: {
    color: muted,
    fontSize: 12,
    fontWeight: '600',
  },
  input: {
    backgroundColor: surface,
    borderColor: border,
    borderRadius: 10,
    borderWidth: 1,
    color: text,
    fontSize: 16,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  codeInput: {
    fontVariant: ['tabular-nums'],
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 50,
  },
  disabledButton: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: accentForeground,
    fontSize: 16,
    fontWeight: '700',
  },
  errorText: {
    color: errorTextColor,
    fontSize: 14,
    lineHeight: 20,
  },
  errorCard: {
    backgroundColor: 'rgba(255, 120, 92, 0.10)',
    borderColor: 'rgba(255, 140, 120, 0.25)',
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  offlineNotice: {
    backgroundColor: isDarkTheme ? 'rgba(245, 196, 81, 0.10)' : '#fff8e7',
    borderColor: isDarkTheme ? 'rgba(245, 196, 81, 0.30)' : '#efc86c',
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  offlineNoticeHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 11,
  },
  offlineNoticeIcon: {
    alignItems: 'center',
    backgroundColor: isDarkTheme ? 'rgba(245, 196, 81, 0.16)' : '#ffedbd',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  offlineNoticeCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  offlineNoticeTitle: {
    color: text,
    fontSize: 16,
    fontWeight: '800',
  },
  offlineNoticeBody: {
    color: muted,
    fontSize: 13,
    lineHeight: 19,
  },
  offlineNoticeActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  offlineNoticeAction: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  offlineNoticeActionPrimary: {
    backgroundColor: accent,
    borderColor: accent,
  },
  offlineNoticeActionText: {
    color: text,
    fontSize: 13,
    fontWeight: '700',
  },
  offlineNoticeActionTextPrimary: {
    color: accentForeground,
  },
  shell: {
    flex: 1,
  },
  main: {
    flex: 1,
  },
  scrollContent: {
    gap: 18,
    padding: 16,
    paddingBottom: 108,
    paddingTop: 20,
  },
  header: {
    gap: 14,
  },
  topBarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: -4,
    justifyContent: 'space-between',
    minHeight: 44,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  homeStickyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingBottom: 4,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 10,
  },
  homeStickyBackground: {
    backgroundColor: bg,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  topBarIconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  filterButtonActive: {
    backgroundColor: panel2,
    borderRadius: 14,
  },
  filterChipRow: {
    gap: 8,
    paddingRight: 16,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: panel,
    borderRadius: 999,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  filterChipSelected: {
    backgroundColor: isDarkTheme ? '#ffffff' : '#000000',
  },
  filterChipText: {
    color: muted,
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextSelected: {
    color: isDarkTheme ? '#000000' : '#ffffff',
  },
  railTitleRow: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    minHeight: 32,
  },
  searchHeader: {
    gap: 12,
  },
  searchHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  searchBox: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minWidth: 0,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  searchClearButton: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderRadius: 999,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  searchCancelButton: {
    alignItems: 'center',
    flexShrink: 0,
    minHeight: 44,
    justifyContent: 'center',
    width: 56,
  },
  searchCancelText: {
    color: text,
    fontSize: 15,
    fontWeight: '600',
  },
  searchInput: {
    color: text,
    flex: 1,
    minWidth: 0,
    fontSize: 16,
    fontWeight: '400',
  },
  metaText: {
    color: muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  sections: {
    gap: 20,
  },
  heroCarousel: {
    alignItems: 'center',
    marginHorizontal: -16,
  },
  heroCard: {
    backgroundColor: panel2,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  heroCardImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroCardShade: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  heroCardFooter: {
    alignItems: 'center',
    bottom: 0,
    gap: 8,
    left: 0,
    padding: 16,
    position: 'absolute',
    right: 0,
    zIndex: 2,
  },
  heroCardTitle: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 30,
    textAlign: 'center',
  },
  heroCardMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  heroCardMeta: {
    color: 'rgba(255,255,255,0.94)',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  heroCardRating: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  heroCardRatingText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  heroPlayButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 10,
    height: 52,
    justifyContent: 'center',
    marginTop: 6,
    width: '100%',
  },
  heroPlayButtonPressed: {
    opacity: 0.82,
  },
  heroPlayButtonText: {
    color: accentForeground,
    fontSize: 18,
    fontWeight: '500',
  },
  posterBadge: {
    alignItems: 'center',
    backgroundColor: '#e5232e',
    borderRadius: 4,
    flexDirection: 'row',
    gap: 4,
    left: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    position: 'absolute',
    top: 6,
  },
  posterBadgeDot: {
    backgroundColor: '#ffd28a',
    borderRadius: 999,
    height: 4,
    width: 4,
  },
  posterBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  rail: {
    gap: 10,
  },
  sectionTitle: {
    color: text,
    fontSize: 20,
    fontWeight: '800',
  },
  railContent: {
    gap: 14,
    paddingRight: 20,
  },
  posterCard: {
  },
  posterFrame: {
    aspectRatio: 2 / 3,
    backgroundColor: panel2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  posterImage: {
    height: '100%',
    width: '100%',
  },
  posterFallback: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 10,
  },
  posterTitle: {
    color: text,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 8,
  },
  posterRatingBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: posterRatingSurface,
    borderColor: posterRatingBorder,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 3,
    position: 'absolute',
    right: 8,
    top: 8,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  posterRatingText: {
    color: posterRatingTextColor,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 13,
  },
  emptyLibrary: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 24,
  },
  emptyLibraryTablet: {
    maxWidth: 520,
  },
  emptyIcon: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 24,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 72,
  },
  emptyIconText: {
    color: accent,
    fontSize: 30,
    fontWeight: '600',
  },
  emptyInline: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 24,
  },
  emptyTitle: {
    color: text,
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyCopy: {
    color: muted,
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 420,
    textAlign: 'center',
  },
  settingsPage: {
    alignSelf: 'center',
    gap: 16,
    maxWidth: settingsContentMaxWidth,
    width: '100%',
  },
  settingsProfile: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 22,
  },
  settingsAvatar: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 36,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    width: 72,
  },
  settingsAvatarText: {
    color: accentForeground,
    fontSize: 18,
    fontWeight: '700',
  },
  settingsProfileTitle: {
    color: text,
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 31,
    marginTop: 12,
  },
  settingsProfileCopy: {
    color: muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    maxWidth: 300,
    textAlign: 'center',
  },
  settingsGroupTitle: {
    color: muted,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginBottom: 8,
    marginLeft: 6,
    textTransform: 'uppercase',
  },
  settingsGroup: {
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
  },
  settingsGroupRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(148,163,184,0.14)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  settingsGroupRowLast: {
    borderBottomWidth: 0,
  },
  settingsRowDangerText: {
    color: dangerText,
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },
  settingsListValue: {
    color: muted,
    fontSize: 14,
    fontWeight: '600',
  },
  settingsListText: {
    color: text,
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
  },
  settingsThemePicker: {
    gap: 10,
    paddingBottom: 16,
    paddingHorizontal: 0,
    paddingTop: 2,
  },
  settingsThemeOptions: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  settingsThemeOption: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderRadius: 12,
    flex: 1,
    gap: 7,
    justifyContent: 'center',
    minHeight: 86,
    paddingHorizontal: 12,
  },
  settingsThemeOptionActive: {
    backgroundColor: accentSoft,
  },
  settingsThemeOptionText: {
    color: muted,
    fontSize: 14,
    fontWeight: '700',
  },
  settingsThemeOptionTextActive: {
    color: accent,
  },
  settingsThemeDivider: {
    backgroundColor: 'rgba(148,163,184,0.18)',
    height: StyleSheet.hairlineWidth,
    width: '100%',
  },
  settingsThemeColorTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '700',
  },
  settingsThemeColorOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  settingsThemeColorOption: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 11,
  },
  settingsThemeColorOptionActive: {
    backgroundColor: accentSoft,
    borderColor: accentBorder,
  },
  settingsThemeColorSwatch: {
    borderRadius: 7,
    height: 22,
    width: 22,
  },
  settingsThemeColorLabel: {
    color: text,
    fontSize: 13,
    fontWeight: '700',
  },
  settingsDetailHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 4,
  },
  settingsDetailHeaderSticky: {
    backgroundColor: bg,
    paddingBottom: 12,
  },
  subpageBackButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  settingsDetailTitle: {
    color: text,
    flex: 1,
    fontSize: 25,
    fontWeight: '700',
    lineHeight: 31,
  },
  settingsCards: {
    gap: 12,
    width: '100%',
  },
  settingsCard: {
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  settingsCardTitle: {
    color: text,
    fontSize: 18,
    fontWeight: '600',
  },
  settingsCardCopy: {
    color: muted,
    flexShrink: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  settingsValue: {
    backgroundColor: surface,
    borderColor: border,
    borderRadius: 10,
    borderWidth: 1,
    color: text,
    fontSize: 13,
    lineHeight: 18,
    padding: 12,
  },
  settingsMetricRows: {
    gap: settingsMetricGap,
  },
  settingsMetricRow: {
    flexDirection: 'row',
    gap: settingsMetricGap,
  },
  settingsMetric: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 11,
    minHeight: 70,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  settingsMetricIcon: {
    alignItems: 'center',
    backgroundColor: accentSoft,
    borderColor: accentBorder,
    borderRadius: 11,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  settingsMetricCopy: {
    flex: 1,
    minWidth: 0,
  },
  settingsMetricValue: {
    color: accent,
    fontSize: 21,
    fontVariant: ['tabular-nums'],
    fontWeight: '800',
    lineHeight: 25,
  },
  settingsMetricLabel: {
    color: muted,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  settingsPrimaryButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
  },
  settingsPrimaryButtonText: {
    color: accentForeground,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
  },
  bottomNav: {
    backgroundColor: colorWithOpacity(panel, 0.88),
    bottom: 0,
    left: 0,
    paddingHorizontal: 6,
    paddingTop: 8,
    position: 'absolute',
    right: 0,
    zIndex: 24,
  },
  bottomNavRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  bottomNavButton: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
    minHeight: 52,
    justifyContent: 'center',
  },
  bottomNavIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 26,
    minWidth: 32,
  },
  bottomNavAvatar: {
    borderRadius: 13,
    height: 26,
    overflow: 'hidden',
    width: 26,
  },
  bottomNavLabel: {
    color: faint,
    fontSize: 10,
    fontWeight: '600',
  },
  bottomNavLabelActive: {
    color: accent,
  },
  miniPlayerWrap: {
    left: 12,
    position: 'absolute',
    right: 12,
    zIndex: 26,
  },
  miniPlayerStrip: {
    alignItems: 'center',
    backgroundColor: 'rgba(23,23,23,0.92)',
    borderColor: 'rgba(255,255,255,0.10)',
    borderRadius: 14,
    borderWidth: 1,
    elevation: 8,
    flexDirection: 'row',
    minHeight: 68,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.34,
    shadowRadius: 18,
  },
  miniPlayerBlur: {
    backgroundColor: 'rgba(23,23,23,0.88)',
  },
  miniPlayerArtworkBackdrop: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.22,
  },
  miniPlayerArtworkBackdropImage: {
    height: '100%',
    transform: [{ scale: 1.06 }],
    width: '100%',
  },
  miniPlayerArtworkBackdropFallback: {
    backgroundColor: '#171717',
    flex: 1,
  },
  miniPlayerArtworkScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  miniPlayerMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 68,
    minWidth: 0,
  },
  miniPlayerThumb: {
    alignItems: 'center',
    backgroundColor: panel2,
    height: 68,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 91,
  },
  miniPlayerThumbImage: {
    height: '100%',
    width: '100%',
  },
  miniPlayerThumbFallback: {
    alignItems: 'center',
    backgroundColor: accent,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  miniPlayerThumbBadge: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    height: 24,
    justifyContent: 'center',
    left: '50%',
    position: 'absolute',
    top: '50%',
    transform: [{ translateX: -12 }, { translateY: -12 }],
    width: 24,
  },
  miniPlayerText: {
    flex: 1,
    minWidth: 0,
  },
  miniPlayerTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
  },
  miniPlayerMeta: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    marginTop: 1,
  },
  miniPlayerDismiss: {
    alignItems: 'center',
    height: 54,
    justifyContent: 'center',
    width: 48,
  },
  pressed: {
    opacity: 0.6,
  },
  playerControlPressed: {
    transform: [{ scale: 0.96 }],
  },
  overlay: {
    backgroundColor: bg,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  detailScroll: {
    paddingBottom: 48,
  },
  detailHero: {
    aspectRatio: 4 / 3,
    position: 'relative',
    width: '100%',
  },
  detailBackdrop: {
    height: '100%',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    left: 0,
    paddingBottom: 8,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 6,
  },
  detailTopBarBackground: {
    backgroundColor: colorWithOpacity(bg, 0.97),
    borderBottomColor: border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  detailTopAction: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  detailTopActions: {
    flexDirection: 'row',
    gap: 8,
  },
  detailStickyTitle: {
    color: '#ffffff',
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  posterSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
    zIndex: 35,
  },
  posterSheet: {
    backgroundColor: panel,
    borderColor: border,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    maxHeight: '86%',
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  posterSheetHandle: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 999,
    height: 4,
    marginBottom: 14,
    width: 42,
  },
  posterSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  posterSheetTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  posterSheetEyebrow: {
    color: accent,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  posterSheetTitle: {
    color: text,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 25,
    marginTop: 2,
  },
  posterSheetClose: {
    alignItems: 'center',
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  posterSheetError: {
    color: errorTextColor,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
  },
  posterCandidateList: {
    gap: 12,
    paddingBottom: 10,
  },
  posterCandidateCard: {
    backgroundColor: panel2,
    borderColor: border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 10,
  },
  posterCandidateTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  posterCandidateImage: {
    backgroundColor: surface,
    borderRadius: 10,
    height: 112,
    overflow: 'hidden',
    width: 76,
  },
  posterCandidateInfo: {
    flex: 1,
    minWidth: 0,
  },
  posterCandidateTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  posterCandidateDetails: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  posterCandidateYear: {
    color: muted,
    fontSize: 12,
    fontWeight: '700',
  },
  posterCandidateSource: {
    borderColor: border,
    borderRadius: 999,
    borderWidth: 1,
    color: muted,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  posterCandidateRating: {
    alignItems: 'center',
    backgroundColor: ratingSurface,
    borderColor: ratingBorder,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  posterCandidateRatingText: {
    color: ratingText,
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 14,
  },
  posterCandidateSummary: {
    color: muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
  },
  posterCandidateGenres: {
    flex: 1,
    color: muted,
    fontSize: 11,
    lineHeight: 16,
  },
  posterCandidateFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  posterCandidateFooterSpacer: {
    flex: 1,
  },
  posterCandidateApply: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 84,
    paddingHorizontal: 12,
  },
  posterCandidateApplyText: {
    color: accentForeground,
    fontSize: 13,
    fontWeight: '900',
  },
  posterCandidateEmpty: {
    alignItems: 'center',
    borderColor: border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    padding: 22,
  },
  posterCandidateEmptyTitle: {
    color: text,
    fontSize: 16,
    fontWeight: '800',
  },
  posterCandidateEmptyCopy: {
    color: muted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  detailTitle: {
    color: text,
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 35,
    textAlign: 'center',
  },
  detailMeta: {
    color: muted,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  detailRatingRow: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: ratingSurface,
    borderColor: ratingBorder,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  detailRatingText: {
    color: ratingText,
    fontSize: 14,
    fontWeight: '800',
  },
  detailBody: {
    gap: 16,
    marginTop: -32,
    paddingHorizontal: 12,
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: accent,
    borderRadius: 12,
    justifyContent: 'center',
    marginTop: 6,
    minHeight: 52,
    overflow: 'hidden',
    position: 'relative',
  },
  playButtonProgress: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  playButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    zIndex: 1,
  },
  playButtonCopy: {
    alignItems: 'flex-start',
  },
  playButtonText: {
    color: accentForeground,
    fontSize: 17,
    fontWeight: '500',
    lineHeight: 20,
  },
  playButtonMeta: {
    color: accentForeground,
    fontSize: 11,
    fontWeight: '500',
    lineHeight: 14,
    opacity: 0.72,
  },
  detailErrorText: {
    color: errorTextColor,
    fontSize: 13,
    lineHeight: 18,
  },
  detailSummary: {
    color: muted,
    fontSize: 14,
    lineHeight: 21,
  },
  detailSummaryBlock: {
    gap: 8,
  },
  detailSummaryToggle: {
    alignSelf: 'flex-start',
    minHeight: 32,
    justifyContent: 'center',
  },
  detailSummaryToggleText: {
    color: accent,
    fontSize: 14,
    fontWeight: '800',
  },
  detailTabs: {
    borderBottomColor: border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 28,
    marginTop: 2,
  },
  detailTabButton: {
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 2,
    position: 'relative',
  },
  detailTabLabel: {
    color: muted,
    fontSize: 18,
    fontWeight: '700',
  },
  detailTabLabelActive: {
    color: text,
  },
  detailTabIndicator: {
    backgroundColor: text,
    bottom: -1,
    height: 3,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  detailsPanel: {
    gap: 22,
    paddingTop: 4,
  },
  detailsSectionHeading: {
    color: text,
    fontSize: 21,
    fontWeight: '700',
  },
  castSection: {
    gap: 12,
  },
  castRailContent: {
    gap: 14,
    paddingRight: 20,
  },
  castCard: {
    alignItems: 'center',
    gap: 4,
    width: 82,
  },
  castAvatar: {
    backgroundColor: panel2,
    borderRadius: 34,
    height: 68,
    overflow: 'hidden',
    width: 68,
  },
  castAvatarImage: {
    height: '100%',
    width: '100%',
  },
  castAvatarFallback: {
    alignItems: 'center',
    backgroundColor: panel2,
    flex: 1,
    justifyContent: 'center',
  },
  castAvatarFallbackText: {
    color: accent,
    fontSize: 22,
    fontWeight: '800',
  },
  castName: {
    color: text,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  castCharacter: {
    color: muted,
    fontSize: 11,
    textAlign: 'center',
  },
  detailsEmpty: {
    color: muted,
    fontSize: 14,
    lineHeight: 21,
  },
  episodesSection: {
    gap: 12,
    paddingTop: 4,
    position: 'relative',
  },
  episodesHeading: {
    color: text,
    fontSize: 21,
    fontWeight: '700',
  },
  seasonPicker: {
    alignItems: 'center',
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  seasonPickerContainer: {
    position: 'relative',
    zIndex: 20,
  },
  seasonPickerText: {
    color: text,
    fontSize: 18,
    fontWeight: '800',
  },
  seasonPickerChevron: {
    transform: [{ rotate: '90deg' }],
  },
  seasonPickerChevronOpen: {
    transform: [{ rotate: '-90deg' }],
  },
  seasonPickerMenu: {
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    elevation: 12,
    gap: 2,
    left: 0,
    marginTop: 4,
    padding: 6,
    position: 'absolute',
    right: 0,
    shadowColor: '#000000',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    top: '100%',
  },
  seasonPickerOption: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  seasonPickerOptionActive: {
    backgroundColor: panel2,
  },
  seasonPickerOptionText: {
    color: muted,
    fontSize: 15,
    fontWeight: '700',
  },
  seasonPickerOptionTextActive: {
    color: text,
  },
  seasonPickerOptionMeta: {
    color: faint,
    fontSize: 12,
    fontWeight: '600',
  },
  episodeList: {
    gap: 14,
  },
  episodeRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 4,
  },
  episodeRowWatched: {
    opacity: 0.62,
  },
  episodeThumb: {
    backgroundColor: panel2,
    borderRadius: 8,
    aspectRatio: 16 / 9,
    overflow: 'hidden',
    position: 'relative',
    width: '38%',
  },
  episodeThumbImage: {
    height: '100%',
    width: '100%',
  },
  episodeThumbFallback: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  episodePlayBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -18,
    marginTop: -18,
    position: 'absolute',
    top: '50%',
    width: 36,
  },
  episodeIndexText: {
    color: accent,
    fontSize: 15,
    fontVariant: ['tabular-nums'],
    fontWeight: '900',
  },
  episodeInfo: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  episodeMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  episodeTitle: {
    color: text,
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 21,
  },
  episodeTitleWatched: {
    color: muted,
  },
  episodeMeta: {
    color: faint,
    fontSize: 12,
    fontWeight: '600',
  },
  episodeSummary: {
    color: muted,
    fontSize: 13,
    lineHeight: 18,
  },
  resumePill: {
    color: accent,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  watchedBadge: {
    alignItems: 'center',
    backgroundColor: '#20c55d',
    borderRadius: 999,
    height: 20,
    justifyContent: 'center',
    position: 'absolute',
    right: 5,
    top: 5,
    width: 20,
  },
  episodeProgressTrack: {
    backgroundColor: 'rgba(255,255,255,0.24)',
    bottom: 0,
    height: 3,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  episodeProgressFill: {
    backgroundColor: accent,
    height: '100%',
  },
  emptyEpisodesCard: {
    backgroundColor: panel,
    borderColor: border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    padding: 14,
  },
  emptyEpisodesTitle: {
    color: text,
    fontSize: 15,
    fontWeight: '600',
  },
  emptyEpisodesCopy: {
    color: muted,
    fontSize: 13,
    lineHeight: 18,
  },
  playerRoot: {
    alignItems: 'center',
    backgroundColor: '#000000',
    justifyContent: 'center',
    zIndex: 30,
  },
  playerVideo: {
    flex: 1,
    width: '100%',
  },
  playerVideoFrame: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  playerVideoFrameFill: {
    flex: 1,
    width: '100%',
  },
  playerStatus: {
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 32,
  },
  playerStatusText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  playerStatusTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  playerRecoveryText: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 420,
    textAlign: 'center',
  },
  playerRecoveryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  playerStatusButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.28)',
    borderRadius: 11,
    borderWidth: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  playerStatusButtonPrimary: {
    backgroundColor: accent,
    borderColor: accent,
  },
  playerStatusButtonPrimaryText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '800',
  },
  playerStatusButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  playerClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    right: 16,
    width: 44,
  },
  playerControls: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  playerTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  playerTopTitle: {
    color: 'rgba(255,255,255,0.82)',
    flex: 1,
    fontSize: 14,
    fontVariant: ['tabular-nums'],
    fontWeight: '800',
  },
  playerTitle: {
    color: '#ffffff',
    fontSize: 21,
    fontWeight: '800',
  },
  playerIconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  playerCloseControl: {
    backgroundColor: 'rgba(18,18,18,0.78)',
    borderRadius: 22,
  },
  playerOptionsPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(18,18,18,0.72)',
    borderRadius: 999,
    flexDirection: 'row',
    paddingHorizontal: 6,
  },
  playerFitButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  playerFitLabel: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  playerFitLabelActive: {
    color: accent,
  },
  playerVideoSettings: {
    paddingHorizontal: 6,
    paddingBottom: 8,
  },
  playerSettingBlock: {
    marginBottom: 16,
  },
  playerSettingLabel: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
  },
  playerSegmentScroll: {
    flexGrow: 0,
  },
  playerSegmented: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  playerSegment: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  playerSegmentActive: {
    backgroundColor: accent,
    borderRadius: 12,
  },
  playerSegmentText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 14,
    fontWeight: '600',
  },
  playerSegmentTextActive: {
    color: '#ffffff',
  },
  playerSegmentDivider: {
    backgroundColor: 'rgba(255,255,255,0.24)',
    height: 24,
    width: 1,
  },
  playerCenterOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  playerCenterRow: {
    alignItems: 'center',
    height: 104,
    justifyContent: 'center',
    position: 'relative',
    width: 392,
  },
  playerSkipButton: {
    alignItems: 'center',
    height: 64,
    justifyContent: 'center',
    width: 64,
  },
  playerSkipBackControl: {
    left: '50%',
    marginLeft: -176,
    marginTop: -32,
    position: 'absolute',
    top: '50%',
  },
  playerSkipForwardControl: {
    left: '50%',
    marginLeft: 112,
    marginTop: -32,
    position: 'absolute',
    top: '50%',
  },
  playerSkipLabel: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 1,
    position: 'absolute',
  },
  playerPlayButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 999,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  playerPlayCenterControl: {
    left: '50%',
    marginLeft: -38,
    marginTop: -38,
    position: 'absolute',
    top: '50%',
  },
  playerBottomBlock: {
    bottom: 28,
    gap: 6,
    left: 28,
    position: 'absolute',
    right: 28,
  },
  playerTimesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  playerTime: {
    color: '#ffffff',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
    fontWeight: '600',
  },
  playerSeekTrackHit: {
    justifyContent: 'center',
    minHeight: 32,
  },
  playerMenuPanel: {
    backgroundColor: 'rgba(14,14,14,0.96)',
    borderColor: 'rgba(255,255,255,0.09)',
    borderRadius: 16,
    borderWidth: 1,
    maxHeight: 260,
    minWidth: 250,
    paddingBottom: 6,
    position: 'absolute',
  },
  playerMenuScroll: {
    paddingHorizontal: 6,
  },
  playerMenuTitle: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingVertical: 12,
    textTransform: 'uppercase',
  },
  playerMenuRow: {
    alignItems: 'center',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  playerMenuRowText: {
    color: '#ffffff',
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 19,
  },
  playerMenuRowTextActive: {
    color: accent,
  },
  playerMenuEmpty: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    lineHeight: 19,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  playerSeekTrack: {
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 2,
    height: 4,
  },
  playerSeekFill: {
    backgroundColor: accent,
    borderRadius: 2,
    height: '100%',
  },
  playerSeekThumb: {
    backgroundColor: accent,
    borderRadius: 7,
    height: 14,
    marginLeft: -7,
    position: 'absolute',
    top: -5,
    width: 14,
  },
  playerGestureHint: {
    alignItems: 'center',
    backgroundColor: 'rgba(12,12,12,0.82)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    left: '50%',
    marginLeft: -82,
    marginTop: -43,
    paddingHorizontal: 18,
    paddingVertical: 12,
    position: 'absolute',
    top: '50%',
    width: 164,
  },
  playerSegmentSkip: {
    alignItems: 'center',
    backgroundColor: 'rgba(12,12,12,0.86)',
    borderColor: 'rgba(255,255,255,0.28)',
    borderRadius: 10,
    borderWidth: 1,
    bottom: 94,
    minHeight: 44,
    paddingHorizontal: 20,
    position: 'absolute',
    right: 28,
    justifyContent: 'center',
    zIndex: 40,
  },
  playerSegmentSkipText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  playerGestureTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  playerGestureTrack: {
    backgroundColor: 'rgba(255,255,255,0.24)',
    borderRadius: 99,
    height: 5,
    marginTop: 10,
    overflow: 'hidden',
    width: '100%',
  },
  playerGestureFill: {
    backgroundColor: accent,
    borderRadius: 99,
    height: '100%',
  },
  playerGestureValue: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
});
}
